## Import the libraries

In [32]:
import torch
import torch.nn as nn
import numpy as np

## Pytorch Examples

In [33]:
X = torch.tensor(([2, 9], [1, 5], [3, 6]), dtype=torch.float) # 3 X 2 tensor
y = torch.tensor(([92], [100], [89]), dtype=torch.float) # 3 X 1 tensor
test_sample = torch.tensor(([4, 8]), dtype=torch.float) # 1 X 2 tensor

In [34]:
print(X.size())
print(y.size())

torch.Size([3, 2])
torch.Size([3, 1])


## Numpy to Pytorch

In [35]:
np.random.seed(42)
numpy_array = np.array(np.random.rand(1000,10))
pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor.size())

torch.Size([1000, 10])


## Start Building Models

In [36]:
class NeuralNetwork(nn.Module):
    def __init__(self ):
        super(NeuralNetwork, self).__init__()
        pass

In [37]:
class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, output_dim, num_hidden):
        super(NeuralNetwork, self).__init__()
        pass

In [38]:
class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, num_hidden):
        super().__init__()
        self.linear1 = nn.Linear(input_dim, num_hidden)
        self.sigmoid = nn.Sigmoid()
        self.linear2 = nn.Linear(num_hidden, 1)

In [39]:
net = NeuralNetwork(10, 5)
net

NeuralNetwork(
  (linear1): Linear(in_features=10, out_features=5, bias=True)
  (sigmoid): Sigmoid()
  (linear2): Linear(in_features=5, out_features=1, bias=True)
)

In [40]:
class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, num_hidden):
        super().__init__()
        self.linear1 = nn.Linear(input_dim, num_hidden)
        self.sigmoid = nn.Sigmoid()
        self.linear2 = nn.Linear(num_hidden, 1)

    def forward(self, x):
        l1 = self.linear1(x)
        activation = self.sigmoid(l1)
        l2 = self.linear2(activation)
        output = self.sigmoid(l2)
        return output

In [41]:
sample = torch.from_numpy(np.array(np.random.rand(10), dtype=np.float32))

In [42]:
sample.size()

torch.Size([10])

In [43]:
net = NeuralNetwork(10, 5)

In [44]:
list(net.linear2.parameters())

[Parameter containing:
 tensor([[ 0.0607, -0.3505, -0.1510, -0.2141,  0.3166]], requires_grad=True),
 Parameter containing:
 tensor([-0.1087], requires_grad=True)]

In [45]:
net.forward(sample)

tensor([0.4365], grad_fn=<SigmoidBackward0>)

In [46]:
class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, num_hidden):
        super().__init__()
        self.linear1 = nn.Linear(input_dim, num_hidden)
        self.sigmoid = nn.Sigmoid()
        self.linear2 = nn.Linear(num_hidden, 1)

    def forward(self, x):
        l1 = self.linear1(x)
        activation = self.sigmoid(l1)
        l2 = self.linear2(activation)
        output = self.sigmoid(l2)
        return output


In [47]:
        

#torch_fit(x_tensor, y_true_tensor, model=model, loss=loss, lr=0.1, num_epochs=30)

loss = nn.BCELoss()
model = NeuralNetwork(10,5)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)



In [48]:
x = np.random.rand(1000,10)
y = np.random.randint(0, 2, 1000)

x_tensor = torch.tensor(x).float()
y_true_tensor = torch.tensor(y).float()
y_true_tensor = y_true_tensor.view(1000, 1) # view function is the same as reshape in numpy

y_pred_tensor = model(x_tensor)
loss_value = loss(y_pred_tensor, y_true_tensor)

In [49]:
print(f"Initial loss: {loss_value.item():.2f}")

Initial loss: 0.70


In [50]:
def torch_fit(x, y, model, loss, lr, num_epochs):
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)   # adam by default and by use case has turned out to be one of the better optimizers  
    for epoch in range(num_epochs):
        optimizer.zero_grad()                                   # to reset the weights and biases before backpropagation as torch already accumulates them during training otherwise 
                                                                # it will keep accumulating the gradients
                                                                # therefor we need to reset the gradients before each step
        y_pred_tensor = model(x_tensor)
        loss_value = loss(y_pred_tensor, y_true_tensor)
        print(f'Epoch {epoch}, loss {loss_value.item():.2f}')
        loss_value.backward()                                   # computes the derivative of the loss w.r.t. the parameters (or anything requiring gradients) using backpropagation.
        optimizer.step()                                        # causes the optimizer to take a step based on the gradients of the parameters.
    return model

model = torch_fit(x_tensor, y_true_tensor, model=model, loss=loss, lr=0.1, num_epochs=100)

Epoch 0, loss 0.70
Epoch 1, loss 0.69
Epoch 2, loss 0.69
Epoch 3, loss 0.69
Epoch 4, loss 0.69
Epoch 5, loss 0.69
Epoch 6, loss 0.69
Epoch 7, loss 0.69
Epoch 8, loss 0.69
Epoch 9, loss 0.69
Epoch 10, loss 0.69
Epoch 11, loss 0.69
Epoch 12, loss 0.69
Epoch 13, loss 0.69
Epoch 14, loss 0.69
Epoch 15, loss 0.69
Epoch 16, loss 0.69
Epoch 17, loss 0.69
Epoch 18, loss 0.69
Epoch 19, loss 0.69
Epoch 20, loss 0.69
Epoch 21, loss 0.69
Epoch 22, loss 0.69
Epoch 23, loss 0.69
Epoch 24, loss 0.69
Epoch 25, loss 0.69
Epoch 26, loss 0.69
Epoch 27, loss 0.69
Epoch 28, loss 0.69
Epoch 29, loss 0.69
Epoch 30, loss 0.69
Epoch 31, loss 0.69
Epoch 32, loss 0.69
Epoch 33, loss 0.69
Epoch 34, loss 0.69
Epoch 35, loss 0.69
Epoch 36, loss 0.69
Epoch 37, loss 0.69
Epoch 38, loss 0.69
Epoch 39, loss 0.69
Epoch 40, loss 0.69
Epoch 41, loss 0.69
Epoch 42, loss 0.69
Epoch 43, loss 0.69
Epoch 44, loss 0.69
Epoch 45, loss 0.69
Epoch 46, loss 0.69
Epoch 47, loss 0.69
Epoch 48, loss 0.69
Epoch 49, loss 0.69
Epoch 50, 